In [1]:
import numpy as np

In [2]:
range(0,10)

range(0, 10)

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
list(range(0,10.5))  # range generate only positive integer not negative and decimal number

TypeError: 'float' object cannot be interpreted as an integer

In [9]:
# solution 
# arange function
np.arange(0,10.5,0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [10]:
np.arange(5,-4,-1)


array([ 5,  4,  3,  2,  1,  0, -1, -2, -3])

In [17]:
np.linspace(0,10,5) # zero se 10 ke scale ko 5 point ko divide krega

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
np.logspace(0,10,5) # same as linespace but log of point

array([1.00000000e+00, 3.16227766e+02, 1.00000000e+05, 3.16227766e+07,
       1.00000000e+10])

In [21]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
np.empty((3,2))

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 1.24610994e-306],
       [1.89146896e-307, 7.56571288e-307]])

In [26]:
a = np.eye(3)

In [28]:
a.shape

(3, 3)

In [29]:
a.size

9

In [30]:
a.ndim

2

# slicing and indexing

In [50]:
a  =np.random.randn(3,4)

In [51]:
a

array([[ 0.08885258,  0.46856456,  0.64864143, -0.31326133],
       [ 1.64459229,  0.56009219,  1.36664591, -1.23111193],
       [-1.67140524,  0.59532743, -0.6129258 ,  0.95715294]])

In [53]:
a[1,2]

np.float64(1.3666459132401925)

In [54]:
a[0:2,1:3]

array([[0.46856456, 0.64864143],
       [0.56009219, 1.36664591]])

In [55]:
a[[0,2],[1,3]]

array([0.46856456, 0.95715294])

# multiply

In [56]:
m1 = np.random.randint(1,3,(3,3))
m1

array([[1, 1, 2],
       [1, 2, 1],
       [2, 1, 2]], dtype=int32)

In [57]:
m2 = np.random.randint(1,3,(3,3))
m2

array([[1, 2, 2],
       [1, 1, 2],
       [2, 2, 2]], dtype=int32)

In [58]:
m1*m2

array([[1, 2, 4],
       [1, 2, 2],
       [4, 2, 4]], dtype=int32)

In [59]:
m1@m2

array([[ 6,  7,  8],
       [ 5,  6,  8],
       [ 7,  9, 10]], dtype=int32)

In [60]:
m1

array([[1, 1, 2],
       [1, 2, 1],
       [2, 1, 2]], dtype=int32)

In [61]:
pow(m1,3)

array([[1, 1, 8],
       [1, 8, 1],
       [8, 1, 8]], dtype=int32)

In [62]:
np.sqrt(m1)

array([[1.        , 1.        , 1.41421356],
       [1.        , 1.41421356, 1.        ],
       [1.41421356, 1.        , 1.41421356]])

In [63]:
np.log(m1)

array([[0.        , 0.        , 0.69314718],
       [0.        , 0.69314718, 0.        ],
       [0.69314718, 0.        , 0.69314718]])

In [65]:
np.log10(m1)

array([[0.     , 0.     , 0.30103],
       [0.     , 0.30103, 0.     ],
       [0.30103, 0.     , 0.30103]])

In [66]:
np.exp(m1)

array([[2.71828183, 2.71828183, 7.3890561 ],
       [2.71828183, 7.3890561 , 2.71828183],
       [7.3890561 , 2.71828183, 7.3890561 ]])

In [67]:
m1**2

array([[1, 1, 4],
       [1, 4, 1],
       [4, 1, 4]], dtype=int32)